// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package catalog

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"context"
	"github.com/derstruct/doors-tutorial/common"
	"github.com/derstruct/doors-tutorial/driver"
	"github.com/doors-dev/doors"
)

type Path = common.CatalogPath

type catalogPage struct {
	// session property
	session *driver.Session
	path    doors.SourceBeam[Path]
}

// state that title depends on
type pathState struct {
	Cat  string
	Item int
}

func (c *catalogPage) Head() templ.Component {
	// derive new beam with pathState
	state := doors.NewBeam(c.path, func(p Path) pathState {
		if p.IsMain {
			return pathState{
				Cat:  "",
				Item: -1,
			}
		}
		if p.IsCat {
			return pathState{
				Cat:  p.CatId,
				Item: -1,
			}
		}
		return pathState{
			Cat:  p.CatId,
			Item: p.ItemId,
		}
	})
	// head component, takes path beam and function to derive HeadData
	return doors.Head(state, func(ps pathState) doors.HeadData {
		// no category selected
		if ps.Cat == "" {
			return doors.HeadData{
				Title: "Catalog",
			}
		}
		cat, ok := driver.Cats.Get(ps.Cat)
		// cat not found
		if !ok {
			return doors.HeadData{
				Title: "Category Not Found",
			}
		}
		// category page
		if ps.Item == -1 {
			return doors.HeadData{
				Title: cat.Name,
				Meta: map[string]string{
					"description": cat.Desc,
				},
			}
		}
		item, ok := driver.Items.Get(ps.Item)
		// item not found
		if !ok {
			return doors.HeadData{
				Title: "Item Not Found",
			}
		}
		return doors.HeadData{
			Title: item.Name,
			Meta: map[string]string{
				"description": item.Desc,
			},
		}
	})
}

func (c *catalogPage) Body() templ.Component {
	// wrap in "Evaluate" component to get access to the context
	return doors.E(func(ctx context.Context) templ.Component {

		// insert session
		common.StoreSession(ctx, c.session)

		// everyting else is same
		b := doors.NewBeam(c.path, func(p Path) bool {
			return p.IsMain
		})
		return doors.Sub(b, func(isMain bool) templ.Component {
			if isMain {
				return main()
			}
			return category(c.path)
		})
	})
}

func (c *catalogPage) Render(b doors.SourceBeam[Path]) templ.Component {
	c.path = b
	return common.Template(c)
}

func Handler(p doors.PageRouter[Path], r doors.RPage[Path]) doors.PageRoute {
	return p.Page(&catalogPage{
		session: common.GetSession(r),
	})
}

var _ = templruntime.GeneratedTemplate
